<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2018/12/2
 * Time: 17:22
 */

namespace app\index\controller;


class Details extends Index
{
    public function index()
    {
        return parent::index(); // TODO: Change the autogenerated stub
    }
}