<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2018/12/2
 * Time: 16:47
 */

namespace app\index\controller;


class Leacots extends Index
{
    public function index()
    {
        return parent::index(); // TODO: Change the autogenerated stub
    }

}